USE ROLE ACCOUNTADMIN;
USE WAREHOUSE BHARATCART_WH;
USE DATABASE BHARATCART_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE OLIST_CUSTOMERS (
    CUSTOMER_ID VARCHAR(32) NOT NULL,
    CUSTOMER_UNIQUE_ID VARCHAR(32) NOT NULL,
    CUSTOMER_ZIP_CODE_PREFIX NUMBER(5,0),
    CUSTOMER_CITY VARCHAR(100),
    CUSTOMER_STATE VARCHAR(2)
);

DESC TABLE OLIST_CUSTOMERS;

CREATE OR REPLACE TABLE OLIST_GEOLOCATION (
    GEOLOCATION_ZIP_CODE_PREFIX NUMBER(5,0),
    GEOLOCATION_LAT FLOAT,
    GEOLOCATION_LNG FLOAT,
    GEOLOCATION_CITY VARCHAR(100),
    GEOLOCATION_STATE VARCHAR(2)
);

CREATE OR REPLACE TABLE OLIST_ORDER_ITEMS (
    ORDER_ID VARCHAR(32),
    ORDER_IDTEM_ID INTEGER,
    PRODUCT_ID VARCHAR(32),
    SHIPPING_LIMIT_DATE TIMESTAMP_NTZ,
    PRICE NUMBER(12,2),
    FRIGHT_VALUE NUMBER(12,2)
);

CREATE OR REPLACE TABLE OLIST_PAYMENTS (
    ORDER_ID VARCHAR(32),
    PAYMENT_SEQUENTIAL INTEGER,
    PAYMENT_TYPE VARCHAR(30),
    PAYMENT_INSTALLMENTS INTEGER,
    PAYMENT_VALUE NUMBER(12,2)
);

CREATE OR REPLACE TABLE OLIST_ORDER_REVIEWS (
    REVIEW_ID VARCHAR(32),
    ORDER_ID VARCHAR(32),
    REVIEW_SCORE INTEGER,
    REVIEW_COMMENT_TITLE VARCHAR,
    REVIEW_COMMENT_MESSAGE VARCHAR,
    REVIEW_CREATION_DATE TIMESTAMP_NTZ,
    REVIEW_ANSWER_TIMESTAMP TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE OLIST_ORDERS (
    ORDER_ID VARCHAR(32),
    CUSTOMER_ID VARCHAR(32),
    ORDER_STATUS VARCHAR(30),
    ORDER_PURCHASE_TIMESTAMP TIMESTAMP_NTZ,
    ORDER_APPROVED_AT TIMESTAMP_NTZ,
    ORDER_DELIVERED_CARRIER_DATE TIMESTAMP_NTZ,
    ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP_NTZ,
    ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE OLIST_PRODUCTS (
    PRODUCT_ID VARCHAR(32),
    PRODUCT_CATEGORY_NAME VARCHAR(100),
    PRODUCT_NAME_LENGTH INTEGER,
    PRODUCT_DESCRIPTION_LENGTH INTEGER,
    PRODUCT_PHOTOS_QTY INTEGER,
    PRODUCT_WEIGHT_G INTEGER,
    PRODUCT_LENGTH_CM INTEGER,
    PRODUCT_HEIGHT_CM INTEGER,
    PRODUCT_WIDTH_CM INTEGER
);

CREATE OR REPLACE TABLE OLIST_SELLERS (
    SELLER_ID VARCHAR(32),
    SELLER_ZIP_CODE_PREFIX NUMBER(5,0),
    SELLER_CITY VARCHAR(100),
    SELLER_STATE VARCHAR(2)
);

CREATE OR REPLACE TABLE PRODUCT_CATEGORY_TRANSLATION (
    PRODUCT_CATEGORY_NAME VARCHAR(100),
    PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR(100)
);

SHOW TABLES IN SCHEMA BHARATCART_DB.RAW;

ALTER TABLE OLIST_PAYMENTS RENAME TO OLIST_ORDER_PAYMENTS;
SHOW TABLES IN SCHEMA BHARATCART_DB.RAW;
